import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://maxi26.com/');
  await page.getByRole('banner').getByRole('link', { name: 'Register' }).click();
  await page.locator('input[name="lname"]').click();
  await page.locator('input[name="lname"]').fill('rahman');
  await page.getByPlaceholder('address-1').click();
  await page.getByPlaceholder('address-1').fill('dhaka');
  await page.getByPlaceholder('address-2').click();
  await page.getByPlaceholder('address-2').fill('dhaka');
  await page.getByPlaceholder('City').click();
  await page.getByPlaceholder('City').fill('djjhka');
  await page.getByPlaceholder('State').click();
  await page.getByPlaceholder('State').fill('dhanmondi');
  await page.getByRole('combobox').selectOption('Bangladesh');
  await page.getByPlaceholder('3423', { exact: true }).click();
  await page.getByPlaceholder('3423', { exact: true }).fill('2356');
  await page.getByPlaceholder('+').click();
  await page.getByPlaceholder('+').fill('01786452733');
  await page.getByPlaceholder('User Name').click();
  await page.getByPlaceholder('User Name').fill('jahan_rahman');
  await page.getByPlaceholder('user@gmail.com').click();
  await page.getByPlaceholder('user@gmail.com').fill('jahan@gmail.com');
  await page.getByPlaceholder('password', { exact: true }).click();
  await page.getByPlaceholder('password', { exact: true }).fill('12345678');
  await page.getByPlaceholder('Confirm password').click();
  await page.getByPlaceholder('Confirm password').fill('12345678');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowLeft');
  await page.getByPlaceholder('User Name').press('ArrowRight');
  await page.getByPlaceholder('User Name').fill('jahanrahman');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
});